In [1]:
import tensorflow as tf
tf.InteractiveSession()

### Tensor of Zeros

In [2]:
tf.zeros(2)

<tf.Tensor 'zeros:0' shape=(2,) dtype=float32>

### Evaluate the value of tensor

In [3]:
a = tf.zeros(2)
a.eval()

array([0., 0.], dtype=float32)

### Evaluate and display value of tensor

In [4]:
a = tf.zeros((2,3))
a.eval()

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [5]:
b = tf.ones((2,2,2))
b.eval()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

### Filling tensor with arbitirary value

In [6]:
c = tf.fill((2,2), value=5.)
c.eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

### Constant tensor

In [7]:
d = tf.constant(5)
d.eval()

5

### Sampling tensor with random entries

In [8]:
f = tf.random_normal((2,2), mean=0, stddev=1)
f.eval()

array([[ 0.19711891, -0.40049344],
       [ 1.086278  ,  1.0306699 ]], dtype=float32)

### Sampling tensor with uniform random entries

In [9]:
g = tf.random_uniform((2,2), minval=-2, maxval=2)
g.eval()

array([[ 0.5050669 ,  0.41151953],
       [ 0.6810322 , -0.31130648]], dtype=float32)

### Tensor addition and scaling

In [10]:
c = tf.ones((2,2))
d = tf.ones((2,2))
e = c + d
e.eval()

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [11]:
f = 2 * e
f.eval()

array([[4., 4.],
       [4., 4.]], dtype=float32)

In [12]:
c = tf.fill((2,2), 2.)
d = tf.fill((2,2), 7.)
e = c * d
e.eval()

array([[14., 14.],
       [14., 14.]], dtype=float32)

### Identity Matrix

In [13]:
a = tf.eye(4)
a.eval()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

### Diagonal matrices

In [14]:
r = tf.range(1,5,1)
r.eval()

array([1, 2, 3, 4], dtype=int32)

In [15]:
d = tf.diag(r)
d.eval()

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]], dtype=int32)

### Transpose of matrix

In [16]:
a = tf.ones((2,3))
a.eval()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [17]:
at = tf.matrix_transpose(a)
at.eval()

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

### Matrix multiplication

In [18]:
a = tf.ones((2,3))
b = tf.ones((3,4))
c = tf.matmul(a,b)
c.eval()

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)

### Dtype of tensors

In [19]:
a = tf.ones((2,2), dtype=tf.int32)
a.eval()

array([[1, 1],
       [1, 1]], dtype=int32)

In [20]:
b = tf.to_float(a)
b.eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

### Tensorflow shapes

In [21]:
a = tf.ones(8)
a.eval()

array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [22]:
b = tf.reshape(a, (4,2))
b.eval()

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [23]:
c = tf.reshape(a, (2,2,2))
c.eval()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

### Expanding and Squeezing tensors

In [24]:
a = tf.ones(2)
a.get_shape()

TensorShape([Dimension(2)])

In [25]:
a.eval()

array([1., 1.], dtype=float32)

In [26]:
b = tf.expand_dims(a, 0)
b.get_shape()

TensorShape([Dimension(1), Dimension(2)])

In [27]:
b.eval()

array([[1., 1.]], dtype=float32)

In [29]:
c = tf.expand_dims(a,1)
c.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [30]:
c.eval()

array([[1.],
       [1.]], dtype=float32)

In [31]:
d = tf.squeeze(b)
d.get_shape()

TensorShape([Dimension(2)])

In [32]:
d.eval()

array([1., 1.], dtype=float32)

### Broadcasting

In [39]:
a = tf.ones((2,2))
a.eval()
b = tf.range(0,2,1, dtype=tf.float32)
b.eval()
c = a+b
c.eval()

array([[1., 2.],
       [1., 2.]], dtype=float32)